"""
Enhanced FastAPI web application for RAG (Retrieval-Augmented Generation) system.
Provides improved security, monitoring, caching, and error handling.
"""

import os
import shutil
import uuid
import re
from typing import List, Optional, Dict, Any
from datetime import datetime, timedelta
from fastapi import FastAPI, File, UploadFile, HTTPException, Request, Depends, BackgroundTasks
from fastapi.responses import HTMLResponse, StreamingResponse, JSONResponse, PlainTextResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from fastapi.security import HTTPBearer
from pydantic import BaseModel
from contextlib import asynccontextmanager
import asyncio

# Import RAG modules
from utils.pdf_manage import get_pdf_names, insert_pdf, set_active_pdfs, query_pdfs_async, query_pdfs_stream_async, delete_pdf
from rag_modules.clear import clear_database
from rag_modules import get_database
from utils.middleware import setup_middleware, rate_limit, log_function_call, get_metrics
from utils.error_handling import (
    setup_exception_handlers, RAGException, ValidationError, FileTooLargeError, 
    InvalidFileTypeError, FileNotFoundError, log_and_raise_error
)
from utils.cache import cache_manager, cache_query
from utils.health import health_checker, health_monitor, HealthStatus
from utils.middleware import logger, PDF_UPLOADS, QUERIES_PROCESSED, ERROR_COUNT
from config import server_settings, security_settings, Config

# Global state
active_pdfs = []
security = HTTPBearer()


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Application lifespan manager"""
    # Startup
    logger.info("Starting RAG System application")
    
    # Create necessary directories
    for directory in ["static", "templates", "uploads", "docs", "database"]:
        os.makedirs(directory, exist_ok=True)
    
    # Start health monitoring
    asyncio.create_task(health_monitor.start_monitoring())
    
    yield
    
    # Shutdown
    logger.info("Shutting down RAG System application")
    health_monitor.stop_monitoring()


# Initialize FastAPI app with lifespan
app = FastAPI(
    title="RAG System",
    description="PDF-based Retrieval-Augmented Generation System",
    version="1.0.0",
    lifespan=lifespan
)

# Setup middleware and exception handlers
setup_middleware(app)
setup_exception_handlers(app)

# Mount static files
app.mount("/static", StaticFiles(directory="static"), name="static")
app.mount("/docs", StaticFiles(directory="docs"), name="docs")
app.mount("/uploads", StaticFiles(directory="uploads"), name="uploads")

# Pydantic models
class QueryRequest(BaseModel):
    query: str
    active_pdfs: List[str]

class SetActivePDFsRequest(BaseModel):
    pdf_names: List[str]

class APIResponse(BaseModel):
    success: bool
    message: str
    data: Optional[Dict[str, Any]] = None


def save_answer_to_file(query: str, answer: str, used_pdfs: List[str]) -> str:
    """Save LLM answer to a file in ./uploads directory"""
    try:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_query = "".join(c for c in query[:50] if c.isalnum() or c in (' ', '-', '_')).rstrip()
        safe_query = safe_query.replace(' ', '_')
        
        filename = f"{timestamp}_{safe_query}.md"
        filepath = os.path.join("uploads", filename)
        
        content = f"""# Query Response - {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Query
{query}

## Used PDFs
{', '.join(used_pdfs)}

## Answer
{answer}

---
*Generated by RAG System*
"""
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        
        logger.info("Answer saved to file", filepath=filepath)
        return filename
        
    except Exception as e:
        logger.error("Error saving answer to file", error=str(e))
        return ""


def validate_pdf_file(file: UploadFile) -> str:
    """Validate and sanitize PDF file"""
    from utils.middleware import SecurityMiddleware
    
    if not file.filename:
        raise ValidationError("No filename provided")
    
    # Check file size
    if hasattr(file, 'size') and file.size > security_settings.max_file_size:
        raise FileTooLargeError(security_settings.max_file_size, file.size)
    
    # Check file extension
    if not file.filename.lower().endswith('.pdf'):
        raise InvalidFileTypeError(['.pdf'], os.path.splitext(file.filename)[1])
    
    # Sanitize filename
    sanitized_filename = SecurityMiddleware.validate_filename(file.filename)
    
    # Ensure unique filename
    base_name, ext = os.path.splitext(sanitized_filename)
    counter = 1
    final_filename = sanitized_filename
    
    while os.path.exists(os.path.join(security_settings.base_upload_dir, final_filename)):
        final_filename = f"{base_name}_{counter}{ext}"
        counter += 1
    
    return final_filename


@app.get("/", response_class=HTMLResponse)
async def home(request: Request):
    """Main page - redirect to React frontend if available"""
    return HTMLResponse("""
    <!DOCTYPE html>
    <html>
    <head>
        <title>RAG System</title>
        <meta http-equiv="refresh" content="0; url=/static/index.html">
    </head>
    <body>
        <p>Redirecting to RAG System frontend...</p>
    </body>
    </html>
    """)


@app.get("/health")
async def health_check():
    """Basic health check endpoint"""
    try:
        health = await health_checker.check_health()
        return {
            "status": health.status,
            "timestamp": health.timestamp,
            "uptime": health.uptime,
            "components": {c.name: c.status for c in health.components}
        }
    except Exception as e:
        logger.error("Health check failed", error=str(e))
        return {"status": "unhealthy", "error": str(e)}


@app.get("/health/detailed")
async def detailed_health_check():
    """Detailed health check with full component information"""
    try:
        health = await health_checker.check_health()
        return health.dict()
    except Exception as e:
        logger.error("Detailed health check failed", error=str(e))
        raise HTTPException(status_code=503, detail=str(e))


@app.get("/metrics")
async def metrics():
    """Prometheus metrics endpoint"""
    try:
        metrics_data = get_metrics()
        return PlainTextResponse(content=metrics_data, media_type="text/plain")
    except Exception as e:
        logger.error("Metrics endpoint failed", error=str(e))
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/api/pdfs")
@rate_limit("50/minute")
@log_function_call("list_pdfs")
async def list_pdfs():
    """Get list of all imported PDF names"""
    try:
        pdf_names = list(get_pdf_names())
        
        # Check cache first
        cache_key = f"pdf_list:{hash(tuple(pdf_names))}"
        cached_result = cache_manager.get(cache_key)
        if cached_result:
            return cached_result
        
        result = {
            "success": True,
            "message": "Retrieved PDF list successfully",
            "data": {"pdfs": pdf_names}
        }
        
        # Cache result
        cache_manager.set(cache_key, result, ttl=300)  # 5 minutes
        
        return result
    except Exception as e:
        log_and_raise_error(DatabaseError, f"Error getting PDF list: {str(e)}", operation="list_pdfs")


@app.post("/upload-pdf")
@rate_limit("10/minute")
@log_function_call("upload_pdf")
async def upload_pdf(background_tasks: BackgroundTasks, file: UploadFile = File(...)):
    """Upload and process a PDF file"""
    try:
        # Validate file
        sanitized_filename = validate_pdf_file(file)
        
        # Build secure upload path
        upload_path = os.path.join(security_settings.base_upload_dir, sanitized_filename)
        
        # Security check - ensure path is within allowed directory
        abs_upload_path = os.path.abspath(upload_path)
        abs_base_dir = os.path.abspath(security_settings.base_upload_dir)
        
        if not abs_upload_path.startswith(abs_base_dir):
            raise ValidationError("Invalid upload path")
        
        # Save uploaded file
        with open(upload_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)
        
        # Process the PDF
        success = await insert_pdf(upload_path)
        
        if success:
            # Invalidate cache
            cache_manager.clear_pattern("pdf_list:*")
            
            # Update metrics
            PDF_UPLOADS.labels(status="success").inc()
            
            # Clear cache for this PDF
            cache_manager.invalidate_pdf_cache(sanitized_filename)
            
            background_tasks.add_task(logger.info, "PDF uploaded successfully", filename=sanitized_filename)
            
            return {
                "success": True, 
                "message": f"Successfully uploaded and processed {sanitized_filename}",
                "data": {"filename": sanitized_filename}
            }
        else:
            PDF_UPLOADS.labels(status="failed").inc()
            raise RAGException("Failed to process PDF", error_code="PROCESSING_ERROR")
            
    except RAGException:
        PDF_UPLOADS.labels(status="failed").inc()
        raise
    except Exception as e:
        PDF_UPLOADS.labels(status="failed").inc()
        log_and_raise_error(ProcessingError, f"Error uploading PDF: {str(e)}", processing_step="upload")


@app.post("/api/set-active-pdfs")
@rate_limit("30/minute")
@log_function_call("set_active_pdfs")
async def set_active_pdfs_endpoint(request: SetActivePDFsRequest):
    """Set which PDFs should be currently used for querying"""
    global active_pdfs
    
    try:
        if len(request.pdf_names) > security_settings.max_pdfs_per_query:
            raise ValidationError(f"Too many PDFs selected. Maximum: {security_settings.max_pdfs_per_query}")
        
        # Validate PDF names exist
        existing_pdfs = list(get_pdf_names())
        invalid_pdfs = set(request.pdf_names) - set(existing_pdfs)
        
        if invalid_pdfs:
            raise ValidationError(f"Invalid PDFs: {list(invalid_pdfs)}")
        
        active_pdfs = request.pdf_names
        success = set_active_pdfs(request.pdf_names)
        
        if success:
            return {
                "success": True,
                "message": f"Successfully set {len(request.pdf_names)} PDFs as active",
                "data": {"active_pdfs": request.pdf_names}
            }
        else:
            raise RAGException("Failed to set active PDFs", error_code="DATABASE_ERROR")
            
    except RAGException:
        raise
    except Exception as e:
        log_and_raise_error(DatabaseError, f"Error setting active PDFs: {str(e)}", operation="set_active_pdfs")


@app.delete("/api/pdfs/{pdf_name}")
@rate_limit("20/minute")
@log_function_call("delete_pdf")
async def delete_pdf_endpoint(pdf_name: str):
    """Delete a specific PDF and all its associated data"""
    global active_pdfs
    
    try:
        # Validate PDF name
        if not pdf_name or any(c in pdf_name for c in ['/', '\\', ':', '*', '?', '"', '<', '>', '|']):
            raise ValidationError("Invalid PDF name")
        
        # Check if PDF exists
        existing_pdfs = list(get_pdf_names())
        if pdf_name not in existing_pdfs:
            raise FileNotFoundError(pdf_name)
        
        # Remove from active PDFs if it's currently active
        if pdf_name in active_pdfs:
            active_pdfs.remove(pdf_name)
            logger.info("Removed PDF from active list", pdf=pdf_name)
        
        # Delete the PDF
        success = delete_pdf(pdf_name)
        
        if success:
            # Clear caches
            cache_manager.clear_pattern("pdf_list:*")
            cache_manager.invalidate_pdf_cache(pdf_name)
            
            return {
                "success": True,
                "message": f"Successfully deleted PDF '{pdf_name}' and all associated data",
                "data": {"deleted_pdf": pdf_name, "remaining_active_pdfs": active_pdfs}
            }
        else:
            raise RAGException(f"Failed to delete PDF '{pdf_name}'", error_code="DATABASE_ERROR")
            
    except RAGException:
        raise
    except Exception as e:
        log_and_raise_error(DatabaseError, f"Error deleting PDF '{pdf_name}': {str(e)}", operation="delete_pdf")


@app.post("/api/query")
@rate_limit("60/minute")
@log_function_call("query")
@cache_query(ttl=1800)  # 30 minutes cache
async def query_endpoint(request: QueryRequest):
    """Answer user's question based on selected PDFs"""
    try:
        if not request.active_pdfs:
            raise ValidationError("No PDFs selected for querying")
        
        if len(request.active_pdfs) > security_settings.max_pdfs_per_query:
            raise ValidationError(f"Too many PDFs selected. Maximum: {security_settings.max_pdfs_per_query}")
        
        # Validate query
        query = request.query.strip()
        if not query:
            raise ValidationError("Query cannot be empty")
        
        if len(query) > security_settings.max_query_length:
            raise ValidationError(f"Query too long. Maximum: {security_settings.max_query_length} characters")
        
        answer = await query_pdfs_async(query, request.active_pdfs)
        
        # Save answer to file
        saved_filename = save_answer_to_file(query, answer, request.active_pdfs)
        
        # Update metrics
        QUERIES_PROCESSED.labels(status="success").inc()
        
        return {
            "success": True,
            "message": "Query processed successfully",
            "data": {
                "query": query,
                "answer": answer,
                "used_pdfs": request.active_pdfs,
                "saved_file": saved_filename
            }
        }
    except RAGException:
        QUERIES_PROCESSED.labels(status="failed").inc()
        raise
    except Exception as e:
        QUERIES_PROCESSED.labels(status="failed").inc()
        log_and_raise_error(ProcessingError, f"Error processing query: {str(e)}", processing_step="query")


@app.post("/api/query/stream")
@rate_limit("60/minute")
@log_function_call("stream_query")
async def query_stream_endpoint(request: QueryRequest):
    """Stream answer for user's question based on selected PDFs"""
    try:
        if not request.active_pdfs:
            raise ValidationError("No PDFs selected for querying")
        
        if len(request.active_pdfs) > security_settings.max_pdfs_per_query:
            raise ValidationError(f"Too many PDFs selected. Maximum: {security_settings.max_pdfs_per_query}")
        
        # Validate query
        query = request.query.strip()
        if not query:
            raise ValidationError("Query cannot be empty")
        
        if len(query) > security_settings.max_query_length:
            raise ValidationError(f"Query too long. Maximum: {security_settings.max_query_length} characters")
        
        full_answer = ""
        
        async def generate_stream():
            nonlocal full_answer
            try:
                async for chunk in query_pdfs_stream_async(query, request.active_pdfs):
                    if chunk:
                        full_answer += chunk
                        yield f"data: {chunk}\n\n"
                
                # Save the complete answer after streaming is done
                if full_answer.strip():
                    saved_filename = save_answer_to_file(query, full_answer, request.active_pdfs)
                    logger.info("Streaming answer saved", filename=saved_filename)
                
                yield "data: [DONE]\n\n"
                QUERIES_PROCESSED.labels(status="success").inc()
                
            except Exception as e:
                logger.error("Stream generation failed", error=str(e))
                yield f"data: Error: {str(e)}\n\n"
                QUERIES_PROCESSED.labels(status="failed").inc()
        
        return StreamingResponse(
            generate_stream(),
            media_type="text/plain",
            headers={
                "Cache-Control": "no-cache",
                "Connection": "keep-alive",
                "Access-Control-Allow-Origin": "*",
                "Access-Control-Allow-Headers": "*",
                "X-Accel-Buffering": "no"
            }
        )
    except RAGException:
        QUERIES_PROCESSED.labels(status="failed").inc()
        raise
    except Exception as e:
        QUERIES_PROCESSED.labels(status="failed").inc()
        log_and_raise_error(ProcessingError, f"Error processing streaming query: {str(e)}", processing_step="stream_query")


@app.delete("/api/clear")
@rate_limit("5/minute")
@log_function_call("clear_database")
async def clear_all_data():
    """Clear all imported PDFs from the database"""
    global active_pdfs
    
    try:
        clear_database()
        active_pdfs = []
        
        # Clear all caches
        cache_manager.clear_pattern("*")
        
        return {
            "success": True,
            "message": "Successfully cleared all data from database"
        }
    except Exception as e:
        log_and_raise_error(DatabaseError, f"Error clearing database: {str(e)}", operation="clear_database")


@app.get("/api/answers")
@rate_limit("100/minute")
async def list_saved_answers():
    """List all saved answer files"""
    try:
        answers_dir = "uploads"
        answer_files = []
        
        if os.path.exists(answers_dir):
            for filename in os.listdir(answers_dir):
                if filename.endswith('.md'):
                    filepath = os.path.join(answers_dir, filename)
                    stat = os.stat(filepath)
                    
                    answer_files.append({
                        "filename": filename,
                        "path": filepath,
                        "size": stat.st_size,
                        "created": datetime.fromtimestamp(stat.st_ctime).strftime("%Y-%m-%d %H:%M:%S"),
                        "modified": datetime.fromtimestamp(stat.st_mtime).strftime("%Y-%m-%d %H:%M:%S")
                    })
        
        # Sort by creation time (newest first)
        answer_files.sort(key=lambda x: x['created'], reverse=True)
        
        return {
            "success": True,
            "message": f"Found {len(answer_files)} saved answers",
            "data": {"answers": answer_files}
        }
    except Exception as e:
        log_and_raise_error(ValidationError, f"Error listing saved answers: {str(e)}")


@app.get("/api/config")
async def get_config():
    """Get public configuration"""
    return {
        "success": True,
        "data": {
            "max_file_size": security_settings.max_file_size,
            "max_query_length": security_settings.max_query_length,
            "max_pdfs_per_query": security_settings.max_pdfs_per_query,
            "allowed_extensions": security_settings.allowed_extensions,
            "rate_limits": {
                "requests": server_settings.rate_limit_requests,
                "window": server_settings.rate_limit_window
            }
        }
    }


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(
        app, 
        host=server_settings.host, 
        port=server_settings.port,
        log_level=server_settings.log_level.lower()
    )