[project]
name = "rag"
version = "0.1.0"
description = "基于Milvus的RAG检索增强生成系统"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.97.1",
    "pymilvus>=2.5.14",
    "requests>=2.31.0"
]
